events:
  MeteorEvent:
    radius: 40
    amountPerPlayer: 5
    lootChance: 0.4
    enemySpawnChance: 0.5
  ZombieHoardEvent:
    waves: 2
    zombiesPerWave: 10
  Sheepocalypse:
    duration: 45
    bombTimer: 10
  LootGoblinEvent:
    speed: 1.0
